const factories=[{name:'익산정밀가공',region:'전북 익산',margin:{cnc:22,sheet:18,print3d:28,injection:25,profile:16,assembly:20},materials:{AL6061:{market:5200,mode:'plusPct',value:18},SUS304:{market:4700,mode:'plusPct',value:22},SS400:{market:1300,mode:'plusWon',value:500},POM:{market:0,mode:'direct',value:8500},ABS:{market:0,mode:'direct',value:4200},PLA:{market:0,mode:'direct',value:3000},PP:{market:0,mode:'direct',value:2400}},rates:{cnc:{small:50000,medium:130000,large:280000,complexMid:20,complexHigh:55,hole:800,tap:2200,setup:80000},sheet:{base:35000,bend:3500,hole:600,tap:1500,paint:60000},print3d:{cm3:350,supportPct:20,complexPct:30,finish:12000},injection:{moldSimple:3000000,moldNormal:5200000,moldComplex:8500000,shot:120,post:60},profile:{m3030:9000,m4040:13000,m4080:23000,cut:1000,tap:1500,bracket:1200},assembly:{simple:60000,normal:160000,complex:330000,inspection:50000,packing:30000}}},{name:'수도권판금테크',region:'경기 시흥',margin:{cnc:25,sheet:16,print3d:30,injection:27,profile:18,assembly:22},materials:{AL6061:{market:5200,mode:'plusPct',value:20},SUS304:{market:4700,mode:'plusWon',value:1200},SS400:{market:1300,mode:'plusPct',value:30},POM:{market:0,mode:'direct',value:9000},ABS:{market:0,mode:'direct',value:4400},PLA:{market:0,mode:'direct',value:3200},PP:{market:0,mode:'direct',value:2500}},rates:{cnc:{small:60000,medium:150000,large:310000,complexMid:25,complexHigh:60,hole:900,tap:2500,setup:90000},sheet:{base:28000,bend:2800,hole:500,tap:1400,paint:55000},print3d:{cm3:420,supportPct:22,complexPct:34,finish:15000},injection:{moldSimple:3500000,moldNormal:5800000,moldComplex:9500000,shot:140,post:70},profile:{m3030:9500,m4040:14000,m4080:24000,cut:1100,tap:1600,bracket:1300},assembly:{simple:70000,normal:190000,complex:380000,inspection:60000,packing:35000}}}];
let selectedFileSize=0;
const $=id=>document.getElementById(id);const money=n=>Math.round(n).toLocaleString('ko-KR')+'원';
function materialUnit(factory, mat){const m=factory.materials[mat];if(!m)return 0;if(m.mode==='plusPct')return m.market*(1+m.value/100);if(m.mode==='plusWon')return m.market+m.value;return m.value;}
function fakeStepAnalysis(){const mb=Math.max(0.4,selectedFileSize/1024/1024||2.2);return{parts:Math.ceil(8+mb*5),unique:Math.ceil(4+mb*2.2),weightKg:Math.max(.2,mb*1.8),volumeCm3:Math.max(80,mb*260),holes:Math.ceil(mb*8),taps:Math.ceil(mb*3),bends:Math.ceil(mb*2.2),cuts:Math.ceil(mb*7),profileM:Math.max(1,mb*2.6),complex:mb>8?'high':mb>3?'mid':'low'}}
function processCost(factory, process, a, mat, qty, finish, assembly){const unit=materialUnit(factory,mat);let materialCost=a.weightKg*unit*qty;let processCost=0;let detail=[];const r=factory.rates[process==='assembly'?'cnc':process];if(process==='cnc'){const base=a.volumeCm3<500?r.small:a.volumeCm3<1800?r.medium:r.large;const complex= a.complex==='high'?r.complexHigh:a.complex==='mid'?r.complexMid:0;processCost=(base*(1+complex/100)+a.holes*r.hole+a.taps*r.tap+r.setup)*Math.max(1,Math.pow(qty,.82));detail.push(['CNC 기본/복잡도/홀탭/셋업',processCost]);}
if(process==='sheet'){processCost=(r.base+a.bends*r.bend+a.holes*r.hole+a.taps*r.tap+(finish==='paint'?r.paint:0))*Math.max(1,Math.pow(qty,.88));detail.push(['판금 기본/절곡/타공/탭',processCost]);}
if(process==='print3d'){processCost=(a.volumeCm3*r.cm3*(1+(a.complex==='high'?r.complexPct:10)/100)+(finish==='sanding'?r.finish:0))*qty;detail.push(['3D 출력 부피/복잡도/후가공',processCost]);}
if(process==='injection'){const mold=a.complex==='high'?r.moldComplex:a.complex==='mid'?r.moldNormal:r.moldSimple;processCost=mold+(r.shot+r.post)*qty;detail.push(['사출 금형/개당 사출/후가공',processCost]);}
if(process==='profile'){processCost=(a.profileM*r.m4040+a.cuts*r.cut+a.taps*r.tap+a.parts*r.bracket)*Math.max(1,Math.pow(qty,.94));detail.push(['프로파일 길이/절단/탭/브라켓',processCost]);}
if(process==='assembly'){const rc=factory.rates.cnc;const rs=factory.rates.sheet;const rp=factory.rates.profile;processCost=(rc.medium*4+rs.base*6+a.bends*rs.bend+rp.m4040*a.profileM+rp.cut*a.cuts);materialCost*=1.4;detail.push(['조립품 부품 제작비 추정',processCost]);}
let finishCost=finish==='none'?0:finish==='anodizing'?60000:finish==='paint'?70000:finish==='plating'?90000:30000;let assy=0;if(assembly!=='no'){const ar=factory.rates.assembly;assy=ar[assembly]+ar.inspection+ar.packing;}const beforeMargin=materialCost+processCost+finishCost+assy;const marginRate=factory.margin[process]??20;const margin=beforeMargin*marginRate/100;return{materialCost,processCost,finishCost,assemblyCost:assy,beforeMargin,marginRate,margin,total:beforeMargin+margin,detail};}
function renderFactories(){const sel=$('factorySelect');sel.innerHTML=factories.map((f,i)=>`<option value="${i}">${f.name} · ${f.region}</option>`).join('');$('mFactories').textContent=factories.length;$('mQuotes').textContent='128';}
function renderRates(){const f=factories[$('factorySelect').value||0];$('factory').innerHTML=`<div class="rateGrid"><div class="rateCard"><h3>${f.name}</h3><p>${f.region}</p><p>플랫폼 수수료 <b>0원</b></p></div>${Object.entries(f.margin).map(([k,v])=>`<div class="rateCard"><h3>${labelProcess(k)}</h3><label>마진율 %<input data-margin="${k}" type="number" value="${v}"></label></div>`).join('')}</div>`;
$('materialTab').innerHTML=`<div class="rateGrid">${Object.entries(f.materials).map(([k,m])=>`<div class="rateCard"><h3>${k}</h3><label>기준 시세<input data-mat="${k}" data-field="market" type="number" value="${m.market}"></label><label>적용 방식<select data-mat="${k}" data-field="mode"><option value="plusPct" ${m.mode==='plusPct'?'selected':''}>시세 + %</option><option value="plusWon" ${m.mode==='plusWon'?'selected':''}>시세 + 원</option><option value="direct" ${m.mode==='direct'?'selected':''}>직접 입력</option></select></label><label>추가값/직접단가<input data-mat="${k}" data-field="value" type="number" value="${m.value}"></label><p>적용단가: <b>${money(materialUnit(f,k))}/kg</b></p></div>`).join('')}</div>`;
$('processTab').innerHTML=`<div class="rateGrid">${Object.entries(f.rates).map(([k,obj])=>`<div class="rateCard"><h3>${labelProcess(k)}</h3>${Object.entries(obj).map(([kk,v])=>`<label>${kk}<input data-rate="${k}" data-key="${kk}" type="number" value="${v}"></label>`).join('')}</div>`).join('')}</div>`;
}
function labelProcess(k){return{cnc:'CNC/MCT',sheet:'판금/절곡',print3d:'3D프린팅',injection:'사출',profile:'프로파일',assembly:'조립'}[k]||k}
function calculate(){const f=factories[$('factorySelect').value];const a=fakeStepAnalysis();const qty=Number($('qty').value||1);const proc=$('process').value;const mat=$('material').value;const finish=$('finish').value;const assembly=$('assembly').value;const q=processCost(f,proc,a,mat,qty,finish,assembly);$('customerPrice').textContent=money(q.total);$('priceRange').textContent=`공장 고객 제출가 범위: ${money(q.total*.92)} ~ ${money(q.total*1.12)} · 플랫폼 수수료 0원`;$('breakdown').innerHTML=[['STEP 추정 부품 수',a.parts+'개'],['STEP 추정 중량',a.weightKg.toFixed(2)+'kg'],['적용 재료단가',money(materialUnit(f,mat))+'/kg'],['재료비',money(q.materialCost)],['공법별 제작비',money(q.processCost)],['후처리비',money(q.finishCost)],['조립/검사/포장',money(q.assemblyCost)],['마진 전 금액',money(q.beforeMargin)],['공법별 업체 마진',q.marginRate+'% · '+money(q.margin)],['고객 제출가',money(q.total)]].map(([a,b])=>`<div class="row"><span>${a}</span><strong>${b}</strong></div>`).join('')+q.detail.map(([a,b])=>`<div class="row"><span>${a}</span><strong>${money(b)}</strong></div>`).join('');}
document.addEventListener('input',e=>{const f=factories[$('factorySelect').value||0];if(e.target.dataset.margin){f.margin[e.target.dataset.margin]=Number(e.target.value||0);renderRates()}if(e.target.dataset.mat){const m=f.materials[e.target.dataset.mat];m[e.target.dataset.field]=e.target.dataset.field==='mode'?e.target.value:Number(e.target.value||0);renderRates()}if(e.target.dataset.rate){f.rates[e.target.dataset.rate][e.target.dataset.key]=Number(e.target.value||0);renderRates()}});
document.querySelectorAll('.tab').forEach(t=>t.onclick=()=>{document.querySelectorAll('.tab,.tabBody').forEach(x=>x.classList.remove('active'));t.classList.add('active');$(t.dataset.tab).classList.add('active')});$('stepFile').onchange=e=>{const file=e.target.files[0];selectedFileSize=file?file.size:0;$('fileName').textContent=file?`${file.name} · ${(file.size/1024/1024).toFixed(2)}MB`:'아직 선택된 파일 없음'};$('calcBtn').onclick=calculate;$('factorySelect').onchange=renderRates;$('resetBtn').onclick=()=>location.reload();renderFactories();renderRates();calculate();
